import { defineNuxtPlugin } from '#app'
import {
  create,
  NAvatar,
  NButton,
  NCard,
  NCheckbox,
  NConfigProvider,
  NDataTable,
  NDatePicker,
  NDialogProvider,
  NDropdown,
  NForm,
  NFormItem,
  NGi,
  NGrid,
  NImage,
  NLayoutHeader,
  NMessageProvider,
  NModal,
  NNotificationProvider,
  NPagination,
  NPopconfirm,
  NSelect,
  NSpin,
  NTag,
  NUpload,
  NUploadDragger,
  NInput,
} from 'naive-ui'

export default defineNuxtPlugin((nuxtApp) => {
  const naive = create({
    components: [
      NAvatar,
      NButton,
      NCard,
      NCheckbox,
      NConfigProvider,
      NDataTable,
      NDatePicker,
      NDialogProvider,
      NDropdown,
      NForm,
      NFormItem,
      NGi,
      NGrid,
      NImage,
      NInput,
      NLayoutHeader,
      NMessageProvider,
      NModal,
      NNotificationProvider,
      NPagination,
      NPopconfirm,
      NSelect,
      NSpin,
      NTag,
      NUpload,
      NUploadDragger,
    ],
  })

  nuxtApp.vueApp.use(naive)
})
